name: "Test"
on:
  pull_request:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE: hello-container

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set the value
        id: step_one
        run: |
          echo "NAME=green" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.NAME }}" # This will output 'yellow'
